setwd("~/work/big-data-analytics-harvard/week1-Jan-29-2016/assignment");
power.consumption.dataframe <- read.delim("2006Data.csv", sep=",");
range(power.consumption.dataframe$Temperature);
temperature_breaks <- seq(0,94,by=2);
tapply(power.consumption.dataframe$Power, cut(power.consumption.dataframe$Temperature, temperature_breaks, right=FALSE), mean);
tapply(power.consumption.dataframe$Power, cut(power.consumption.dataframe$Temperature, temperature_breaks, right=FALSE), min);
tapply(power.consumption.dataframe$Power, cut(power.consumption.dataframe$Temperature, temperature_breaks, right=FALSE), max);
power.consumption.matrix <- matrix(tapply(power.consumption.dataframe$Power, cut(power.consumption.dataframe$Temperature, temperature_breaks, right=FALSE), mean));
power.consumption.matrix <- cbind(power.consumption.matrix, tapply(power.consumption.dataframe$Power, cut(power.consumption.dataframe$Temperature, temperature_breaks, right=FALSE), min));
power.consumption.matrix <- cbind(power.consumption.matrix, tapply(power.consumption.dataframe$Power, cut(power.consumption.dataframe$Temperature, temperature_breaks, right=FALSE), max));
colnames(power.consumption.matrix) <- c("average.power", "min.power", "max.power");
power.consumption.matrix;
install.packages("ggplot2");
library("ggplot2");
power.consumption.metrics.dataframe <- data.frame(power.consumption.matrix);
ggplot(power.consumption.metrics.dataframe) + geom_point(aes(x =rownames(power.consumption.metrics.dataframe), y = average.power), color="blue",size=1) + geom_point(aes(x =rownames(power.consumption.metrics.dataframe), y = min.power), color="red",size=1) + geom_point(aes(x =rownames(power.consumption.metrics.dataframe), y = max.power), color="green",size=1) + xlab("Temperature") + ylab("Power Consumption");
average.power.consumption.matrix <- matrix(average.temperatures.vector);
average.power.consumption.matrix <- cbind(average.power.consumption.matrix, tapply(power.consumption.dataframe$Power, cut(power.consumption.dataframe$Temperature, temperature_breaks , right=FALSE), mean));
colnames(average.power.consumption.matrix) <- c("average.temperature", "average.power.consumption");
average.power.consumption.matrix;
var(average.power.consumption.matrix);
min.power.consumption.matrix <- matrix(average.temperatures.vector);
min.power.consumption.matrix <- cbind(min.power.consumption.matrix, tapply(power.consumption.dataframe$Power, cut(power.consumption.dataframe$Temperature, temperature_breaks , right=FALSE), min));
colnames(min.power.consumption.matrix) <- c("average.temperature", "min.power.consumption");
min.power.consumption.matrix;
var(min.power.consumption.matrix);
max.power.consumption.matrix <- matrix(average.temperatures.vector);
max.power.consumption.matrix <- cbind(max.power.consumption.matrix, tapply(power.consumption.dataframe$Power, cut(power.consumption.dataframe$Temperature, temperature_breaks , right=FALSE), max));
colnames(max.power.consumption.matrix) <- c("average.temperature", "max.power.consumption");
max.power.consumption.matrix;
var(max.power.consumption.matrix);