V <- c(7,2,1,0,3,-1,-3,4);
V;
A <- matrix(V, nrow=4);
A;
AT <- t(A);
AT;
A %*% AT;
AT %*% A;
solve(A %*% AT);
det(A %*% AT);
solve(AT %*% A);
det(AT %*% A);
V;
V <- c(V, c(-2));
V;
B <- matrix(V, nrow=3);
B;
Binv <- solve(B);
Binv;
round(B %*% Binv);
round(Binv %*% B);
eigen(B);
C <- eigen(B)$vectors;
class(C);
C %*% B;
B %*% C;
det(C %*% B);
det(B %*% C);
dimnames(B) <- list(c("R1", "R2", "R3"), c("C1", "C2", "C3"));
B;
B.data.frame <- data.frame(B);
B.data.frame;
class(B.data.frame);

